version: '3'
services:
  website:
    image: alidockerad/my-custom-website:v1
    ports:
      - "8080:80"
    networks:
      - app-net
    restart: always

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mehaboob123
      MYSQL_DATABASE: mydb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-net
    restart: always

volumes:
  db-data:

networks:
  app-net:

