apiVersion: v1
data:
  password: SW5mcmFAMTIz
  username: bWVoYWJvb2I=
kind: Secret
metadata:
  creationTimestamp: "2026-09-12T10:44:49Z"
  name: my-secret
  namespace: default
  resourceVersion: "5297"
  uid: 18a7fe1e-2d5c-4b11-af25-409e5f4a3cd3
type: Opaque
