apiVersion: v1
data:
  index.html: |
    <h1>Hello Mehaboob - Day 24 Live!</h1>
    <p>InfraCloud Journey - ConfigMap Success</p>
kind: ConfigMap
metadata:
  creationTimestamp: "2026-09-12T10:22:21Z"
  name: my-html
  namespace: default
  resourceVersion: "4213"
  uid: 8c261a16-c1b9-4aa5-918a-9f33e12c515b
